strategy:
  matrix:
    windows-stable:
      imageName: 'windows-2019'
      rustup_toolchain: nightly
    mac-stable:
      imageName: 'macos-10.14'
      rustup_toolchain: nightly
    linux-stable:
      imageName: 'ubuntu-18.04'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cd packages/catalyst-common && cargo build --all --verbose
    displayName: Cargo build
  - script: cd packages/catalyst-common && cargo test --all --verbose
    displayName: Cargo test
  - script: cd packages/catalyst-common && cargo test --features key-gen
    displayName: Cargo test key-gen build