[package]
name = "catalyst-ffi"
version = "0.1.0"
authors = ["fran <fran.sl@atlascity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catalyst-common = { path = "../catalyst-common", features=["random-generation"] }
libc = "0.2.66"
